services:
  - type: web
    name: marketplace_audioshop
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn shop.wsgi:application"
    staticDirs:
      - path:  /media
        serve:  /media
    disk:
      name: media
      mountPath:  /media